###  introduction: Welcome to the World of Numpy!


**Understanding Numpy Arrays — Your Personal Assistant for Data**

Imagine you’re managing a list of room prices for different suites in your hotel. You have Deluxe, Executive, and Presidential rooms. Normally, you might use a spreadsheet, but Numpy’s arrays allow you to manage these lists in a much more efficient way.

#### Let’s start by creating a list of room prices:

In [1]:
import numpy as np

# Prices for Deluxe, Executive, and Presidential rooms
room_prices = np.array([120, 220, 450])
print(room_prices)


[120 220 450]


#### Here, room_prices is a Numpy array — a powerful structure that allows you to do quick calculations, just like calculating total revenue or the average price of rooms.

**Key Concepts:**

Numpy arrays can hold multiple data points, just like columns in a spreadsheet, but they are faster and easier to manipulate.
Creating arrays is simple and helps you manage data effectively.

**Matrix Creation and Manipulation**

Now imagine you’re managing multiple hotel branches across different cities, and you need to keep track of room prices for each branch. You’ll need something more than just a list — a matrix!

A matrix is like a 2D array, where rows and columns can hold data about different branches and room types. Let’s create a matrix to keep track of room prices for three branches in three different cities.

In [2]:
# Room prices for three cities: [Deluxe, Executive, Presidential]
branch_prices = np.array([[120, 220, 450], 
                          [130, 240, 460], 
                          [115, 210, 440]])

print(branch_prices)


[[120 220 450]
 [130 240 460]
 [115 210 440]]


In [3]:
# Create a matrix representing monthly sales data for your restaurant across three branches. Perform basic manipulations like changing the shape or calculating the total sales.





Now, you have a 3x3 matrix where each row represents a branch, and each column represents a room type.

**Key Concepts:**

Matrices are multidimensional arrays, perfect for handling complex datasets.
You can perform manipulations like transposing (flipping rows and columns), reshaping, and combining matrices.

#### Indexing, Slicing, and Reshaping

Let’s say you only want to analyze the room prices of the Deluxe suites across all your branches. You can use indexing to pull out just the data you need.

In [4]:
# Extract Deluxe room prices (column 0)
deluxe_prices = branch_prices[:, 0]
print(deluxe_prices)


[120 130 115]


**You can also slice parts of your data, like selecting the first two branches only:**

In [5]:
# Slice the first two branches (rows 0 and 1)
subset = branch_prices[0:2, :]
print(subset)


[[120 220 450]
 [130 240 460]]


**Need to reorganize your data? You can reshape it into different dimensions**

In [7]:
# Reshape to a 9x1 matrix
reshaped_prices = branch_prices.reshape(9, 1)
print(reshaped_prices)


[[120]
 [220]
 [450]
 [130]
 [240]
 [460]
 [115]
 [210]
 [440]]


**Key Concepts:**

Indexing lets you grab specific data points.

Slicing allows you to take out chunks of data.

Reshaping lets you reorganize your data for different analysis purposes.

**Basic Arithmetic Operations**

In the hospitality industry, you often need to apply discounts or calculate totals. Numpy makes this a breeze by allowing you to perform arithmetic operations on entire arrays or matrices at once.

Let’s say there’s a special 10% discount on all room prices. You can apply this discount easily:

In [8]:
# Apply a 10% discount on all prices
discounted_prices = branch_prices * 0.9
print(discounted_prices)


[[108.  198.  405. ]
 [117.  216.  414. ]
 [103.5 189.  396. ]]


##### You can also sum up your data, such as calculating the total revenue from all rooms:

In [9]:
# Calculate total room prices for each branch
total_revenue = np.sum(branch_prices, axis=1)
print(total_revenue)


[790 830 765]


**Key Concepts:**

You can apply arithmetic operations like addition, multiplication, and division to arrays.

Use Numpy to quickly calculate totals, averages, or apply discounts.

In [ ]:
# Activity: Simulate applying a 15% discount to food prices in your restaurant and calculate the new total bill.





####  Broadcasting — Scaling Operations Across Arrays

Imagine you need to add a service fee of $20 to each room in your hotel across all branches. Instead of manually doing this for each entry, Numpy’s broadcasting feature can automatically apply this change across the entire array.



In [11]:
# Add a service fee of $20 to all room prices
service_fee_added = branch_prices + 20
print(service_fee_added)


[[140 240 470]
 [150 260 480]
 [135 230 460]]


**Key Concept:**

Broadcasting automatically applies operations to arrays, making it super efficient for applying changes across datasets.

**Conclusion: You're Now a Numpy Ninja**

Congratulations! You’ve learned how to use Numpy to streamline and enhance your data handling in the hospitality industry. From managing room prices to calculating discounts and total revenue, you now have the tools to make data work for you — fast and efficiently.